// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipzmgntkhafmwxtoxmzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlwem1nbnRraGFmbXd4dG94bXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjcwMTgsImV4cCI6MjA2ODk0MzAxOH0.0HCCCbpXqMVnX2FFDNywr-ccmcj8GdGOEDjqtd4So7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});